### ISSUE TITLE
UIAlertController dismissWith.... methods should dismiss the view controller

### ISSUE THREAD

**Issue by tooluser** [pivotal/PivotalCoreKit#134]
One of the actions taken by UIAlertController on click of any block is to dismiss itself. (Apple's docs don't state this explicitly, but it is observed behavior, viz:

>Typically the alert controller is dismissed automatically when the user selects an action. It can also be dismissed programmatically, if required, like any other view controller.

(from [UseYourLoaf](http://useyourloaf.com/blog/2014/09/05/uialertcontroller-changes-in-ios-8.html).)

The current utility methods:
```
- (void)dismissByTappingCancelButton {
    UIAlertAction *cancelAction = [self cancelAction];
    if (cancelAction.handler) {
        cancelAction.handler(cancelAction);
    }
}

- (void)dismissByTappingButtonWithTitle:(NSString *)title {
    UIAlertAction *action = [self actionWithButtonTitle:title];
    if (action.handler) {
        action.handler(action);
    }
}
```

Don't dismiss the VC, so don't mimic the real-world behavior and make testing tough; it's not possible to verify that the alert VC was dismissed.

**Comment by tjarratt** [comment]
Closed by #135. Thanks for the contribution, @tooluser!
