### ISSUE TITLE
Not all schemes are building with Carthage

### ISSUE THREAD

**Issue by mjstallard** [pivotal/PivotalCoreKit#176]
@jfoley and I are trying to use PCK (on master) with Carthage. We've got to the point where PCK appears to build without an error (by using the fix in PR #175), however we only see the following schemes being built:

```
± ms+jf |master ✗| → carthage update --no-use-binaries --platform ios
...
*** Building scheme "CoreLocation+PivotalSpecHelper-iOS" in PivotalCoreKit.xcworkspace
*** Building scheme "UIKit+PivotalCore-iOS" in PivotalCoreKit.xcworkspace
*** Building scheme "WatchKit" in PivotalCoreKit.xcworkspace
*** Building scheme "Cedar-iOS" in PivotalCoreKit.xcworkspace
...
```

There's a number of schemes missing (notable for us are the spec helpers and stubs). Having spoken with @younata, it appears that this could be a bug in Carthage, but we're filing an issue here to track this on the PCK side.

**Comment by akitchen** [comment]
I wouldn't expect Carthage to build targets that aren't dynamic frameworks. can you confirm you are building a version of PCK where these targets are in fact dynamic frameworks?  Previously these targets were static frameworks built by a series of scripts inside an Xcode scheme, which Carthage doesn't support.

**Comment by mjstallard** [comment]
Yes, we were building against master (which I understand has the dynamic frameworks as canonical targets).

**Comment by younata** [comment]
I'm not seeing this on my end.

installed latest carthage master using their tools `git clone git@github.com:/Carthage/Carthage.git && cd Carthage && sudo make install`, then go to PCK w/ latest (after a `git submodule update`), and run `carthage build --no-skip-current` builds all the dynamic frameworks.

Current carthage release (0.11) doesn't work, because the pull request that enables support for projects structured like PCK was merged after that release was cut. As of this comment, they haven't made another release. However, Mike is definitely aware of that.

**Comment by idoru** [comment]
Had some time to follow up on this today. I have also just verified with carthage 0.15.2 that master appears to build all 19 frameworks:

```
± |master ✓| → carthage build --no-skip-current
*** xcodebuild output can be found in /var/folders/j_/wwl3kb7d6mld45lx8cmpdzqh0000gn/T/carthage-xcodebuild.uCk5hz.log
*** Building scheme "CoreLocation+PivotalSpecHelper-watchOS" in PivotalCoreKit.xcworkspace
*** Building scheme "CoreLocation+PivotalSpecHelper" in PivotalCoreKit.xcworkspace
*** Building scheme "CoreLocation+PivotalSpecHelper-tvOS" in PivotalCoreKit.xcworkspace
*** Building scheme "CoreLocation+PivotalSpecHelper-iOS" in PivotalCoreKit.xcworkspace
*** Building scheme "Foundation+PivotalSpecHelper-tvOS" in PivotalCoreKit.xcworkspace
*** Building scheme "Foundation+PivotalCore" in PivotalCoreKit.xcworkspace
*** Building scheme "Foundation+PivotalCore-tvOS" in PivotalCoreKit.xcworkspace
*** Building scheme "Foundation+PivotalCore-watchOS" in PivotalCoreKit.xcworkspace
*** Building scheme "Foundation+PivotalSpecHelper" in PivotalCoreKit.xcworkspace
*** Building scheme "Foundation+PivotalSpecHelper-iOS" in PivotalCoreKit.xcworkspace
*** Building scheme "Foundation+PivotalSpecHelper-watchOS" in PivotalCoreKit.xcworkspace
*** Building scheme "Foundation+PivotalCore-iOS" in PivotalCoreKit.xcworkspace
*** Building scheme "UIKit+PivotalCore-tvOS" in PivotalCoreKit.xcworkspace
*** Building scheme "UIKit+PivotalSpecHelperStubs-tvOS" in PivotalCoreKit.xcworkspace
*** Building scheme "UIKit+PivotalSpecHelper-tvOS" in PivotalCoreKit.xcworkspace
*** Building scheme "UIKit+PivotalCore-iOS" in PivotalCoreKit.xcworkspace
*** Building scheme "UIKit+PivotalSpecHelper-iOS" in PivotalCoreKit.xcworkspace
*** Building scheme "UIKit+PivotalSpecHelperStubs-iOS" in PivotalCoreKit.xcworkspace
*** Building scheme "WatchKit" in PivotalCoreKit.xcworkspace
```

Unless I missed something, this doesn't appear to be an issue anymore, so I'm going to close it.
